import React from "react";

import "../Main/Main.css";
import FoodList from "../FoodList/FoodList";
import NavLinks from "../NavLinks/NavLinks";

const Main = ({
  foodMenu,
  addToCart,
  userInfo,
  cost,
  setCost,
  pizzaBtnValue,
  soupsBtnValue,
  snacksBtnValue,
  coldSnacksBtnValue,
  iceCreamBtnValue,
  saladsBtnValue,
  pastesBtnValue,
  beerSnacksBtnValue,
  hotDishesBtnValue,
  setPizzaBtnValue,
  setSoupsBtnValue,
  setSnacksBtnValue,
  setColdSnacksBtnValue,
  setIceCreamBtnValue,
  setSaladsBtnValue,
  setPastesBtnValue,
  setBeerSnacksBtnValue,
  setHotDishesBtnValue,
  deleteElementInMenu,
  openPopupAddItem,
  cigarettesBtnValue,
  hookahsBtnValue,
  juiceBtnValue,
  coffeesBtnValue,
  teaBtnValue,
  bottledBeerBtnValue,
  wineBtnValue,
  champagneBtnValue,
  vermouthBtnValue,
  aperativesBtnValue,
  rumBtnValue,
  cognacBtnValue,
  brandyBtnValue,
  whiskeyBtnValue,
  ginBtnValue,
  tequilaBtnValue,
  tincturesBtnValue,
  vodkaBtnValue,
  liqueursBtnValue,
  cocktailsBtnValue,
  shotsBtnValue,
  setCigarettesBtnValue,
  setHookahsBtnValue,
  setJuiceBtnValue,
  setCoffeeBtnValue,
  setTeaBtnValue,
  setBottledBeerBtnValue,
  setWineBtnValue,
  setChampagneBtnValue,
  setVermouthBtnValue,
  setAperativesBtnValue,
  setRumBtnValue,
  setCognacBtnValue,
  setBrandyBtnValue,
  setWhiskeyBtnValue,
  setGinBtnValue,
  setTequilaBtnValue,
  setTincturesBtnValue,
  setVodkaBtnValue,
  setLiqueursBtnValue,
  setCocktailsBtnValue,
  setShotsBtnValue,
  btnBar,
  setBtnBar,
  btnFood,
  setBtnFood,
  foodMenuBar,
  deleteElementInBarMenu,
  setDeleteCard,
  openPopupConfirm,
  openPopupChangeInfo
}) => {

  console.log('foodArrayInMain', foodMenu)
  return (
    <main className="main">
      <NavLinks
        setPizzaBtnValue={setPizzaBtnValue}
        setSoupsBtnValue={setSoupsBtnValue}
        setColdSnacksBtnValue={setColdSnacksBtnValue}
        setIceCreamBtnValue={setIceCreamBtnValue}
        setSnacksBtnValue={setSnacksBtnValue}
        setSaladsBtnValue={setSaladsBtnValue}
        setPastesBtnValue={setPastesBtnValue}
        setBeerSnacksBtnValue={setBeerSnacksBtnValue}
        setHotDishesBtnValue={setHotDishesBtnValue}
        pizzaBtnValue={pizzaBtnValue}
        soupsBtnValue={soupsBtnValue}
        snacksBtnValue={snacksBtnValue}
        coldSnacksBtnValue={coldSnacksBtnValue}
        iceCreamBtnValue={iceCreamBtnValue}
        saladsBtnValue={saladsBtnValue}
        pastesBtnValue={pastesBtnValue}
        beerSnacksBtnValue={beerSnacksBtnValue}
        hotDishesBtnValue={hotDishesBtnValue}
        cigarettesBtnValue={cigarettesBtnValue}
        hookahsBtnValue={hookahsBtnValue}
        juiceBtnValue={juiceBtnValue}
        coffeesBtnValue={coffeesBtnValue}
        teaBtnValue={teaBtnValue}
        bottledBeerBtnValue={bottledBeerBtnValue}
        wineBtnValue={wineBtnValue}
        champagneBtnValue={champagneBtnValue}
        vermouthBtnValue={vermouthBtnValue}
        aperativesBtnValue={aperativesBtnValue}
        rumBtnValue={rumBtnValue}
        cognacBtnValue={cognacBtnValue}
        brandyBtnValue={brandyBtnValue}
        whiskeyBtnValue={whiskeyBtnValue}
        ginBtnValue={ginBtnValue}
        tequilaBtnValue={tequilaBtnValue}
        tincturesBtnValue={tincturesBtnValue}
        vodkaBtnValue={vodkaBtnValue}
        liqueursBtnValue={liqueursBtnValue}
        cocktailsBtnValue={cocktailsBtnValue}
        shotsBtnValue={shotsBtnValue}
        setCigarettesBtnValue={setCigarettesBtnValue}
        setHookahsBtnValue={setHookahsBtnValue}
        setJuiceBtnValue={setJuiceBtnValue}
        setCoffeeBtnValue={setCoffeeBtnValue}
        setTeaBtnValue={setTeaBtnValue}
        setBottledBeerBtnValue={setBottledBeerBtnValue}
        setWineBtnValue={setWineBtnValue}
        setChampagneBtnValue={setChampagneBtnValue}
        setVermouthBtnValue={setVermouthBtnValue}
        setAperativesBtnValue={setAperativesBtnValue}
        setRumBtnValue={setRumBtnValue}
        setCognacBtnValue={setCognacBtnValue}
        setBrandyBtnValue={setBrandyBtnValue}
        setWhiskeyBtnValue={setWhiskeyBtnValue}
        setGinBtnValue={setGinBtnValue}
        setTequilaBtnValue={setTequilaBtnValue}
        setTincturesBtnValue={setTincturesBtnValue}
        setVodkaBtnValue={setVodkaBtnValue}
        setLiqueursBtnValue={setLiqueursBtnValue}
        setCocktailsBtnValue={setCocktailsBtnValue}
        setShotsBtnValue={setShotsBtnValue}
        btnBar={btnBar}
        setBtnBar={setBtnBar}
        btnFood={btnFood}
        setBtnFood={setBtnFood}
      />
      <FoodList
        foodArray={foodMenu}
        addToCart={addToCart}
        cart={false}
        userInfo={userInfo}
        setCost={setCost}
        pizzaBtnValue={pizzaBtnValue}
        soupsBtnValue={soupsBtnValue}
        coldSnacksBtnValue={coldSnacksBtnValue}
        iceCreamBtnValue={iceCreamBtnValue}
        snacksBtnValue={snacksBtnValue}
        saladsBtnValue={saladsBtnValue}
        pastesBtnValue={pastesBtnValue}
        beerSnacksBtnValue={beerSnacksBtnValue}
        hotDishesBtnValue={hotDishesBtnValue}
        deleteElementInMenu={deleteElementInMenu}
        openPopupAddItem={openPopupAddItem}
        cigarettesBtnValue={cigarettesBtnValue}
        hookahsBtnValue={hookahsBtnValue}
        juiceBtnValue={juiceBtnValue}
        coffeesBtnValue={coffeesBtnValue}
        teaBtnValue={teaBtnValue}
        bottledBeerBtnValue={bottledBeerBtnValue}
        wineBtnValue={wineBtnValue}
        champagneBtnValue={champagneBtnValue}
        vermouthBtnValue={vermouthBtnValue}
        aperativesBtnValue={aperativesBtnValue}
        rumBtnValue={rumBtnValue}
        cognacBtnValue={cognacBtnValue}
        brandyBtnValue={brandyBtnValue}
        whiskeyBtnValue={whiskeyBtnValue}
        ginBtnValue={ginBtnValue}
        tequilaBtnValue={tequilaBtnValue}
        tincturesBtnValue={tincturesBtnValue}
        vodkaBtnValue={vodkaBtnValue}
        liqueursBtnValue={liqueursBtnValue}
        cocktailsBtnValue={cocktailsBtnValue}
        shotsBtnValue={shotsBtnValue}
        foodMenuBar={foodMenuBar}
        btnBar={btnBar}
        btnFood={btnFood}
        deleteElementInBarMenu={deleteElementInBarMenu}
        openPopupConfirm={openPopupConfirm}
        openPopupChangeInfo={openPopupChangeInfo}
      />
    </main>
  );
};
export default Main;
